#!/usr/bin/env ruby
# This file is adapted from Ruby on Rails (https://github.com/rails/rails).
# Copyright (c) David Heinemeier Hansson, licensed under the MIT License.
# See https://github.com/rails/rails/blob/main/MIT-LICENSE
require_relative "../config/boot"
require "active_support/continuous_integration"

CI = ActiveSupport::ContinuousIntegration
require_relative "../config/ci.rb"
